modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/mrmelon54/draggable_lists/issues"
license = "GPL-3.0-only"

[[mods]]
modId = "draggable_lists"
version = "${version}"
displayName = "Draggable Lists"
authors = "MrMelon54"
description = "${description}"
logoFile = "/icon.png"

[[dependencies.draggable_lists]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.draggable_lists]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.draggable_lists]]
modId = "cloth_config"
mandatory = true
versionRange = "[${cloth_config_version},)"
ordering = "AFTER"
side = "BOTH"
